In [7]:
import numpy as np

np_array = np.array([1,2,4,6])
print(type(np_array))
print('Array size', np_array.size)
print('Array dtype', np_array.dtype)
print('Array shape', np_array.shape)
print('Array n dinmension', np_array.ndim)

<class 'numpy.ndarray'>
Array size 4
Array dtype int32
Array shape (4,)
Array n dinmension 1


In [37]:
arr_array = np.arange(2, 20, 2)
# arr_array = np.arange(2, 20)
# print(arr_array)

#to convert to look like matrix 3x3
arr_array=arr_array.reshape(3,3)
print(arr_array)# to shape in 3X3
print(arr_array.shape) #to print shape
print(arr_array.size) #size of the item on the array
print('Array n dinmension', arr_array.ndim)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
(3, 3)
9
Array n dinmension 2


In [11]:
arr_array = np.arange(2, 37, 2)
# arr_array = np.arange(2, 20)
# print(arr_array)

# #to convert to look like matrix 3x3
arr_array=arr_array.reshape(3,3,2)
print(arr_array)# to shape in 3X3
print(arr_array.shape) #to print shape
print(arr_array.size) #size of the item on the array
# print('Array n dimension', arr_array.ndim)
# print('*******\n---After reshape-----***')
# print(arr_array)
# print('Array n dimension', arr_arry_reshaped.ndim)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
(24,)
24
Array n dimension 1
*******
---After reshape-----***
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


NameError: name 'arr_arry_reshaped' is not defined

In [19]:
arr_array = np.arange(1, 25)
# arr_array = np.arange(2, 20)
# print(arr_array)

#to convert to look like matrix 3x3
arr_array=arr_array.reshape(3,3)
print(arr_array)# to shape in 3X3
print(arr_array.shape) #to print shape
print(arr_array.size) #size of the item on the array
# print('Array n dinmension', arr_array.ndim)

ValueError: cannot reshape array of size 24 into shape (3,3)

In [53]:
arr_array = np.arange(3, 73, 3)
# arr_array = np.arange(2, 20)
print(arr_array)

# #to convert to look like matrix 3x3
arr_array=arr_array.reshape(3,3,3)
print(arr_array)# to shape in 3X3
print(arr_array.shape) #to print shape
print(arr_array.size) #size of the item on the array
print('Array n dinmension', arr_array.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72]


ValueError: cannot reshape array of size 24 into shape (3,3,3)

In [51]:
#numpy linspace : is for generating numbers in range and divide into equal interval
arr = np.linspace(2,5,5)
print(arr)
print(arr.size)

[2.   2.75 3.5  4.25 5.  ]


In [57]:
# ones_array = np.ones(10)
# print(ones_array)

ones_array = np.ones(6)
print(ones_array.reshape(2,3))

zeros_array =  np.zeros(10)
print(zeros_array)

[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [59]:
array = np.arange(2,20) #the number of items
print(array)

aray1=np.append(array, 40) #to add 40
print(aray1)

aray1=np.delete(array, -2) #delete
print(aray1)



[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 40]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 19]


In [66]:
array_random = np.random.rand(10)
print(array_random)
sorted_array = np.sort(array_random)
print(sorted_array)

print("to generate random numbers")
random_item = np.random.random()
print("random number", round(random_item * 100,2))#to generate random number

[0.12368988 0.27059436 0.41152754 0.08934457 0.46051932 0.29464785
 0.14098709 0.15998148 0.10977047 0.79972994]
[0.08934457 0.10977047 0.12368988 0.14098709 0.15998148 0.27059436
 0.29464785 0.41152754 0.46051932 0.79972994]
to generate random numbers
random number 75.01


In [68]:
array_random = np.random.rand(3,4)
print(array_random)
array_random = array_random * 10
print(array_random)

[[0.72118781 0.99271083 0.44677223 0.46070726]
 [0.64691249 0.74193363 0.40934717 0.03774271]
 [0.82103776 0.18377027 0.69693383 0.75515251]]
[[7.21187806 9.92710835 4.46772226 4.60707264]
 [6.46912486 7.41933631 4.09347168 0.37742705]
 [8.21037761 1.83770271 6.96933831 7.5515251 ]]


In [71]:
array_a = np.arange(1, 10)
array_b = np.arange(11, 20)

#reshape
array_a = array_a.reshape(3,3)
array_b = array_b.reshape(3,3)
print('************')
print('array_a', array_a)
print('array_b', array_b)
array_c = array_b + array_a
print("array_c:", array_c)

************
array_a [[1 2 3]
 [4 5 6]
 [7 8 9]]
array_b [[11 12 13]
 [14 15 16]
 [17 18 19]]
array_c: [[12 14 16]
 [18 20 22]
 [24 26 28]]
